# Generated by Django 5.2.5 on 2025-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SB', 'Svalbard'), ('CR', 'Costa Rica'), ('NC', 'Nicaragua'), ('HD', 'Honduras'), ('GUA', 'Guatemala'), ('UZ', 'Uzbekistan'), ('VN', 'Vietnam')])),
                ('image', models.ImageField(upload_to='static/arts/<django.db.models.fields.CharField>')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
