# Generated by Django 5.2.5 on 2025-11-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_product_date_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
