# Generated by Django 5.2.5 on 2025-11-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_file',
        ),
    ]
