# Generated by Django 5.2.5 on 2025-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_rename_image_product_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aspect_ratio',
            field=models.CharField(choices=[('2:1', '2:1'), ('1:1', '1:1'), ('1:2', '1:2')], default='1:1'),
            preserve_default=False,
        ),
    ]
