# Generated by Django 5.2.5 on 2025-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_product_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('WA', 'Water color'), ('WC', 'Wax Crayons'), ('FL', 'Fine liner'), ('GUA', 'Guache')], default='FL'),
        ),
    ]
