# Generated by Django 5.2.5 on 2025-12-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_product_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(default='Water colors', verbose_name=['Water colors', 'Wax Crayons', 'Color pencils', 'Guache', 'Mixed', 'Fine liner']),
        ),
    ]
