# Generated by Django 5.2.5 on 2025-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_product_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='geocoor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('WA', 'Water colors'), ('WC', 'Wax Crayons'), ('CP', 'Color pencils'), ('GUA', 'Guache'), ('MX', 'Mixed'), ('FL', 'Fine liner')], default='Water colors'),
        ),
    ]
