# Generated by Django 5.2.5 on 2025-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_product_geocoor_alter_product_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='geocoor',
            field=models.CharField(default='80.0000, 90.0000', max_length=100),
        ),
    ]
