# Generated by Django 5.2.5 on 2025-12-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_alter_product_geocoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
