# Generated by Django 5.2.5 on 2025-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_people_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('WA', 'Water colors'), ('WC', 'Wax Crayons'), ('CP', 'Color pencils'), ('GUA', 'Guache'), ('MX', 'Mixed'), ('FL', 'Fine liner'), ('CR', 'Crayons')], default='Water colors'),
        ),
    ]
