# Generated by Django 5.2.5 on 2025-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_rename_category_product_country_alter_product_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AddField(
            model_name='product',
            name='category_choices',
            field=models.CharField(choices=[('LS', 'Landscapes'), ('ARC', 'Architecture'), ('PP', 'People'), ('AN', 'Animals'), ('OBJ', 'Objects')], default='Landscapes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='geocoor',
            field=models.CharField(default='80.00, 80.00', max_length=100),
        ),
    ]
