# Generated by Django 5.2.5 on 2025-12-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_remove_product_featured_product_category_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_choices',
            new_name='category',
        ),
    ]
