# Generated by Django 5.2.5 on 2025-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_rename_category_choices_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Ger', 'Germany'), ('SB', 'Svalbard'), ('CR', 'Costa Rica'), ('NC', 'Nicaragua'), ('HD', 'Honduras'), ('GUA', 'Guatemala'), ('UZ', 'Uzbekistan'), ('VN', 'Vietnam')]),
        ),
    ]
