# Generated by Django 5.2.5 on 2025-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_alter_product_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Ger', 'Germany'), ('SB', 'Svalbard'), ('CR', 'Costa Rica'), ('NC', 'Nicaragua'), ('HD', 'Honduras'), ('GUA', 'Guatemala'), ('UZ', 'Uzbekistan'), ('VN', 'Vietnam'), ('POR', 'Portugal')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('WA', 'Water colors'), ('WC', 'Wax Crayons'), ('CP', 'Color pencils'), ('GUA', 'Guache'), ('MX', 'Mixed'), ('FL', 'Fine liner'), ('CR', 'Crayons'), ('IN', 'Ink')], default='Water colors'),
        ),
    ]
