# Generated by Django 5.2.5 on 2025-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_alter_product_country_alter_product_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Germany', 'Germany'), ('Svalbard', 'Svalbard'), ('Costa Rica', 'Costa Rica'), ('Nicaragua', 'Nicaragua'), ('Honduras', 'Honduras'), ('Guatemala', 'Guatemala'), ('Uzbekistan', 'Uzbekistan'), ('Vietnam', 'Vietnam'), ('Portugal', 'Portugal')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('Water colors', 'Water colors'), ('Wax Crayons', 'Wax Crayons'), ('Color pencils', 'Color pencils'), ('Guache', 'Guache'), ('Mixed', 'Mixed'), ('Fine liner', 'Fine liner'), ('Crayons', 'Crayons'), ('Ink', 'Ink')], default='Water colors'),
        ),
    ]
