# Generated by Django 5.2.5 on 2025-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_alter_product_country_alter_product_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Landscapes', 'Landscapes'), ('Architecture', 'Architecture'), ('People', 'People'), ('Animals', 'Animals'), ('Objects', 'Objects')], default='Landscapes'),
        ),
    ]
