# Generated by Django 5.2.5 on 2026-02-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('artist', 'Artist'), ('subject', 'Subject / depicted'), ('collaborator', 'Collaborator'), ('curator', 'Curator')], default='subject', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.artist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.product')),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AddField(
            model_name='product',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='products', through='maps.Person', to='maps.artist'),
        ),
    ]
