# Generated by Django 5.2.5 on 2026-02-22 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_product_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.CharField(choices=[('artist', 'Artist'), ('subject', 'Subject / depicted'), ('other', 'Other')], default='subject', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
