# Generated by Django 5.2.5 on 2026-02-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_alter_person_roles_alter_product_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='person',
            name='order',
        ),
        migrations.RemoveField(
            model_name='person',
            name='product',
        ),
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Moorboor', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('artist', 'Artist'), ('subject', 'Subject / depicted'), ('other', 'Other')], default='subject', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.product')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='products', through='maps.ProductPerson', to='maps.person'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
