# Generated by Django 5.2.5 on 2026-02-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_remove_person_artist_remove_person_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to='maps.person'),
            preserve_default=False,
        ),
    ]
