# Generated by Django 5.2.5 on 2026-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_product_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperson',
            name='roles',
            field=models.CharField(choices=[('subject', 'Subject / depicted'), ('other', 'Other')], default='subject', max_length=30),
        ),
    ]
