# Generated by Django 5.2.5 on 2026-02-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_alter_productperson_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
