# Generated by Django 5.2.5 on 2026-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_file',
            field=models.ImageField(null=True, upload_to='static/person'),
        ),
    ]
