# Generated by Django 5.2.5 on 2026-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_person_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.ImageField(upload_to='arts/'),
        ),
    ]
