# Generated by Django 5.2.5 on 2026-02-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_alter_product_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_file',
            field=models.ImageField(null=True, upload_to='people/'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/carousel/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='maps.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
